### PR TITLE
WIP:Rivulet2 Neuron Tracing Plugin

### PR DESCRIPTION
**Pull request by lsqshr**
Implemented Rivulet2 algorithm to overwrite Rivulet plugin since Rivulet2 simply works better & only has one parameter (I believe the background threshold is something cannot be discarded). 

Works now & Will keep updating it & will merge it myself when it's fully tested.

### CODE REVIEW

**Comment by zhizhoualan** [comment]
Great! Thanks!

**Comment by lsqshr** [comment]
Hi @zhizhoualan, which gcc version you guys normally use to build vaa3d release version? Is c++11 supported?

**Comment by zhizhoualan** [comment]
We are using gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-3). But I think c++11
is supported.

**Comment by lsqshr** [comment]
Thanks for confirming @zhizhoualan I will have a try to make sure.

**Comment by zhizhoualan** [comment]
After adding one line in the pro file to enable c++11 flag, I can build
your plugin on my Linux machine now.

Cheers,

Zhi

**Comment by lsqshr** [comment]
That saved hours Zhi! Thanks for your help!!

**Pull request merged**
